[build]
  command = "bun run build"
  publish = ".output/public"
  functions = ".output/server"

[dev]
  command = "bun run dev"
  targetPort = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200