[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions-internal/server/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions-internal/server"
  status = 200
  force = true
